dataset:
  ann_path : './data/splits'
  path : './data'
  save_dir : './results'
  name : 'fast_ixi'
  target_size : !<tag:yaml.org,2002:seq> [128,128]
  batch_size : 1

model:
  backbone : 'resnet18'
  target_dimension : 448
  output_dimension : 180 # After applying random dimensionality reduction