dataset:
  ann_path : '/home/mamur/TUM/Seminar/data/splits'
  path : '/home/mamur/TUM/Seminar/data'
  name : 'fast_ixi' # fast , ixi, fast_ixi
  resize : 128
  cropsize : 128
  batch_size : 1

model:
  backbone : 'resnet18'
