dataset:
  ann_path : '/home/guests/usr_mlmi/arda/padim/data/splits'
  path : '/home/guests/usr_mlmi/arda/padim/data'
  save_dir : '/home/guests/usr_mlmi/arda/padim/Unsupervised-Anomaly-Detection-in-Medical-Images-via-PaDiM/results'
  name : 'fast_ixi'
  resize : 128
  cropsize : 128
  batch_size : 1

model:
  backbone : 'resnet18'